### ISSUE TITLE
Add cross references

### ISSUE THREAD

**Issue by postiffm** [postiffm/bibledit-desktop#86]
Add openbible.info cross references to analysis window. And/or Treasury Scripture Knowledge cross-references. These would be added alongside of the other cross-refs we already have. BUT, I would like them to be differentiated somehow so that the user can tell..."these cross-refs came from Bibles International; these ones came from openbible.info; these other ones came from TSK."

**Comment by Pickle** [comment]
I had a similar thought on this (but with the bibles) if a copyright
statement should be below the verse in the smaller font size.
Would that meet your expectations?

**Comment by postiffm** [comment]
I was thinking we might make the Bibles and cross-references windows similar, each with a link at the bottom that says "For version and copyright information, click here" and it would pop up a dialog box. Or, we could have a dialog box accessible from, say, the Help menu, that would display the same information.

**Comment by postiffm** [comment]
Or, with the Bibles, where it says "NET" or "EMT" or "SBL" we could make that text be a hyperlink so that if you click it, a window would open up with copyright and other necessary attribution info.

**Comment by postiffm** [comment]
One way that we might make it easy on ourselves is to have the copyright info in a README in each directory (engmtv, slbgnt, etc.) and then the dialog box can just read in that information and display it. Then no matter how many Bibles or other such data sets we have, we can just walk through each and every one, grab the info, and add it to the display. It might be a long window full of text, but that is fine. No one looks at this stuff hardly anyway.

**Comment by Pickle** [comment]
So your idea of the copyright page seems to fit with the requirements of
Bible.org for example:
https://bible.org/article/trademark-and-copyright-information

If you quote the NET Bible in your entire work in lieu of saying *NET* after
each scripture you may include the following acknowledgement on your
acknowledgement page

   - " Scripture quoted by permission. All scripture quotations, unless
   otherwise indicated, are taken from the NET Bible® copyright ©1996-2018 by
   Biblical Studies Press, L.L.C. All rights reserved."

**Comment by postiffm** [comment]
This is done with comitt e400813, which added the openbible cross reference database, about 380,000 xrefs. Since this database is derived from the Treasury of Scripture Knowledge, I'm going to close this issue out for now. More xrefs can always be added later.
